spring:
  datasource:
    url: jdbc:mysql://localhost:13308/mod_technology
    username: root
    password: just4mysql

server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

config.name: dev