spring:
  application:
    name: security-service

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

jwt:
  issuer: FSD - Mentor On Demand
  secret: Mod4FsD
  validity: 18000
