server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/xulix/fsd-backend.git
          search-paths: config-repo
#        native:
#          search-locations: file:/Users/lauro/Documents/Workspace/fsd/mod/backend/config-repo
#        bootstrap: true
  profiles:
    active: native

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

